---
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add Docker apt key.
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: false
    checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

- name: Add Docker repository.
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install Docker packages.
  ansible.builtin.apt:
    name:
      - "docker-{{ docker_edition }}"
      - "docker-{{ docker_edition }}-cli"
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: present
  notify: Restart docker

- name: Ensure Docker is started and enabled at boot.
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - docker
    - containerd
