---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install PIP dependencies.
      pip:
        name: docker
        state: present

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
 
  tasks:
    - name: "Include serversideup.docker_swarm"
      include_role:
        name: "serversideup.docker_swarm"
